### ISSUE TITLE
Showing permission not granted even after granting administrative permissions , also shows some errors in fetching contest details.

### ISSUE THREAD

**Issue by HridayAg0102** [cheran-senthil/TLE#463]
I have been trying to put roles on users after handle identification , but I am repeatedly getting this error 

``````
30-06-2021 13:40:08:ERROR:tle.util.discord_common:Ignoring exception in command handle identify:
Traceback (most recent call last):
  File "/home/hriday/.cache/pypoetry/virtualenvs/tle-tnVDVzjZ-py3.8/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/hriday/Desktop/TLE/tle/util/codeforces_common.py", line 85, in f
    await fun(self, ctx, *args, **kwargs)
  File "/home/hriday/Desktop/TLE/tle/cogs/handles.py", line 396, in identify
    await self._set(ctx, ctx.author, user)
  File "/home/hriday/Desktop/TLE/tle/cogs/handles.py", line 366, in _set
    await self.update_member_rank_role(member, role_to_assign,
  File "/home/hriday/Desktop/TLE/tle/cogs/handles.py", line 339, in update_member_rank_role
    await member.add_roles(role_to_assign, reason=reason)
  File "/home/hriday/.cache/pypoetry/virtualenvs/tle-tnVDVzjZ-py3.8/lib/python3.8/site-packages/discord/member.py", line 664, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/home/hriday/.cache/pypoetry/virtualenvs/tle-tnVDVzjZ-py3.8/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hriday/.cache/pypoetry/virtualenvs/tle-tnVDVzjZ-py3.8/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/hriday/.cache/pypoetry/virtualenvs/tle-tnVDVzjZ-py3.8/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1329, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/hriday/.cache/pypoetry/virtualenvs/tle-tnVDVzjZ-py3.8/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/hriday/.cache/pypoetry/vi
``````

I have given the bot Administrative permissions , but it is still showing issues. Can I get some help regarding this. 

Just for confirmation , do I need to paste the permission number anywhere in the script of the bot ? (eg. Administrator : 8)

![image](https://user-images.githubusercontent.com/76818035/124132011-ff20ea80-da9d-11eb-9f90-7b02e06eb2e3.png)

**Comment by iampjeetsingh** [comment]
Have you made all the codeforces roles?
If yes, make sure that codeforces role is above those roles.

**Comment by HridayAg0102** [comment]
ok , I'll try that as well , Thanks for help

**Comment by HridayAg0102** [comment]
Thanks for help, the issue is sorted 😄
