### ISSUE TITLE
Not able to switch pages, throws error saying two factor is required for this operation

### ISSUE THREAD

**Issue by iampjeetsingh** [cheran-senthil/TLE#464]
```
future: <Task finished coro=<Paginated.paginate() done, defined at /home/paramjeet/Applications/Bots/TLE/tle/util/paginator.py:51> exception=Forbidden('403 Forbidden (error code: 60003): Two factor is required for this operation')>
Traceback (most recent call last):
  File "/home/paramjeet/Applications/Bots/TLE/tle/util/paginator.py", line 71, in paginate
    await reaction.remove(user)
  File "/home/paramjeet/.cache/pypoetry/virtualenvs/tle-4jQ8yAYZ-py3.7/lib/python3.7/site-packages/discord/reaction.py", line 122, in remove
    await self.message.remove_reaction(self.emoji, user)
  File "/home/paramjeet/.cache/pypoetry/virtualenvs/tle-4jQ8yAYZ-py3.7/lib/python3.7/site-packages/discord/message.py", line 1033, in remove_reaction
    await self._state.http.remove_reaction(self.channel.id, self.id, emoji, member.id)
  File "/home/paramjeet/.cache/pypoetry/virtualenvs/tle-4jQ8yAYZ-py3.7/lib/python3.7/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 60003): Two factor is required for this operation
```

**Comment by iampjeetsingh** [comment]
This exception is raised when the discord server is a community server and the owner of the bot hasn't enabled 2fa on his account. Enabling 2fa fixes this.
