### ISSUE TITLE
Not working with python 3.10

### ISSUE THREAD

**Issue by asandikci** [cheran-senthil/TLE#499]
Hello,
I was just using this bot with python3.7 and after upgrading to python3.10 bot is not working. When I was trying to run "poetry install"   there are some issues like:

```
~/TLE$ poetry install
Installing dependencies from lock file

Package operations: 7 installs, 0 updates, 0 removals

  • Installing scipy (1.6.1): Failed

  EnvCommandError

  Command ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/bin/pip', 'install', '--no-deps', 'file:///home/asandikci/.cache/pypoetry/artifacts/bc/74/e2/a22451059efb69c32be2d51a7727b1133375122dd7564e8a8e9df4f1cd/scipy-1.6.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/asandikci/.cache/pypoetry/artifacts/bc/74/e2/a22451059efb69c32be2d51a7727b1133375122dd7564e8a8e9df4f1cd/scipy-1.6.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [112 lines of output]
        setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-v_zfa0dy'), proceeding with generating Cython sources and expanding templates
          warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
        Running from SciPy source directory.
        INFO: lapack_opt_info:
        INFO: lapack_armpl_info:
        INFO: customize UnixCCompiler
        INFO:   libraries armpl_lp64_mp not found in ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: lapack_mkl_info:
        INFO:   libraries mkl_rt not found in ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: openblas_lapack_info:
        INFO:   libraries openblas not found in ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: openblas_clapack_info:
        INFO:   libraries openblas,lapack not found in ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: flame_info:
        INFO:   libraries flame not found in ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: accelerate_info:
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_3_10_threads_info:
        INFO: Setting PTATLAS=ATLAS
        INFO:   libraries tatlas,tatlas not found in /home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib
        INFO:   libraries tatlas,tatlas not found in /usr/local/lib
        INFO:   libraries tatlas,tatlas not found in /usr/lib64
        INFO:   libraries tatlas,tatlas not found in /usr/lib
        INFO:   libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
        INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_3_10_info:
        INFO:   libraries satlas,satlas not found in /home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib
        INFO:   libraries satlas,satlas not found in /usr/local/lib
        INFO:   libraries satlas,satlas not found in /usr/lib64
        INFO:   libraries satlas,satlas not found in /usr/lib
        INFO:   libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
        INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_threads_info:
        INFO: Setting PTATLAS=ATLAS
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
        INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_info:
        INFO:   libraries f77blas,cblas,atlas not found in /home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib
        INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
        INFO: <class 'numpy.distutils.system_info.atlas_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: lapack_info:
        INFO:   libraries lapack not found in ['/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
        INFO:   NOT AVAILABLE
        INFO:
        /tmp/pip-build-env-bbtn7eja/overlay/lib/python3.10/site-packages/numpy/distutils/system_info.py:1902: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        INFO: lapack_src_info:
        INFO:   NOT AVAILABLE
        INFO:
        /tmp/pip-build-env-bbtn7eja/overlay/lib/python3.10/site-packages/numpy/distutils/system_info.py:1902: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        INFO:   NOT AVAILABLE
        INFO:
        Traceback (most recent call last):
          File "/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/home/asandikci/.cache/pypoetry/virtualenvs/tle-mFxh8Sm3-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "/tmp/pip-build-env-bbtn7eja/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/tmp/pip-build-env-bbtn7eja/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 253, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/tmp/pip-build-env-bbtn7eja/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 145, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 588, in <module>
            setup_package()
          File "setup.py", line 584, in setup_package
            setup(**metadata)
          File "/tmp/pip-build-env-bbtn7eja/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 135, in setup
            config = configuration()
          File "setup.py", line 499, in configuration
            raise NotFoundError(msg)
        numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
        To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
        See site.cfg.example in the Scipy source directory and
        https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  

  at ~/.local/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

```

Note: "asandikci" is my username.
I'm not sure if this problem is about python3.10 but bot was working on python3.7 properly. I hope you can help

**Comment by asandikci** [comment]
@algmyr its working for now, thanks!
